#!/bin/bash

rm -f */document.ransom

rm -f */test-???.png

rm -f */*-enc.png */xor*.png */*.kra

rm -f */sha */pbkdf2

#rm -f */server/sessionkey */server/encryptionkey
#rm -rf */server/__pycache__ */server/venv */server/*.pyc
